/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface McButton {
    }
}
declare global {
    interface HTMLMcButtonElement extends Components.McButton, HTMLStencilElement {
    }
    var HTMLMcButtonElement: {
        prototype: HTMLMcButtonElement;
        new (): HTMLMcButtonElement;
    };
    interface HTMLElementTagNameMap {
        "mc-button": HTMLMcButtonElement;
    }
}
declare namespace LocalJSX {
    interface McButton {
    }
    interface IntrinsicElements {
        "mc-button": McButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mc-button": LocalJSX.McButton & JSXBase.HTMLAttributes<HTMLMcButtonElement>;
        }
    }
}
